source 'https://rubygems.org'

gem 'pry-byebug'
gem 'rspec', '= 3.5'
#gem 'openstack', '~> 3.3'
gem 'fog-openstack'
gem 'thor', '~> 0.20.3'
gem 'bolt', '~> 1.9'
gem 'rspec-puppet', '~> 2.7'
gem 'diff_matcher', '~> 2.4'
