#! /usr/bin/env ruby

$LOAD_PATH << File.expand_path(File.join(File.dirname(__FILE__),'..','lib'))
require 'osc/open_stack_control'

osc = OSC::OpenStackControl.process(ARGV)
begin
  osc.run
rescue OSC::OSCError => e
  puts e.message
end
exit osc.exit_code
